fix:Standardization of folders to kebab-case. modifed home - add avat…
Devathon-2024-team5/preguntonic_FrontEnd pull request #11
Opened 2024-04-16 18:43 UTC by NicolasLLans

# Description:

Add name and avatar selection. And a function that captures and the data in a json that prints through the console.
Standardization of folders to kebab-case.
Changed the name of the UI folder to components to avoid conflicts when naming the folder that will contain components.

# Trello link:

[https://trello.com/c/7pliEbQS/<Edit This>](https://trello.com/c/FeMnxVdc/65-vista-p%C3%A1gina-de-inicio-y-sala-de-espera)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

2024-04-16 18:57 UTC, WanderleeDev approved these changes

2024-04-17 00:18 UTC, Alejandro25AR commented on src/app/components/avatar-Image/avatar-image.component.css
> +  background-color: var(--game-clr-green) !important;
Change variable with --accent-color

2024-04-17 02:47 UTC, Alejandro25AR commented on src/app/components/avatar-Image/avatar-image.component.css
> +  background-color: var(--game-clr-yellow) !important;
Normally the use of "!important" is bad practice

2024-04-17 02:49 UTC, Alejandro25AR commented on src/app/components/custom-Button/custom-button.component.css
Lowercase "Button".

2024-04-17 02:53 UTC, Alejandro25AR commented on src/app/components/avatar-Image/avatar-image.component.css
Lowercase the folder name to "avatar-image".

2024-04-17 03:08 UTC, Alejandro25AR commented on src/app/pages/home/home.component.html
>          <h1 class="text-center title-y">Elegí un avatar y escribí tu nombre</h1>
Change the title to a more neutral tone to "Selecciona un avatar"".

2024-04-17 03:10 UTC, Alejandro25AR commented on src/app/pages/home/home.component.html
> +            placeholder="Escribí tu nombre"
Change the placeholder to "Nombre" only.

2024-04-17 03:11 UTC, Alejandro25AR commented on src/app/pages/home/home.component.html
> +      <app-custom-button (click)="iniciarPartida()">Iniciar partida</app-custom-button>
El texto del botón no describe la acción que realmente realiza, cámbialo por "Crear sala".

2024-04-17 03:25 UTC, Alejandro25AR requested changes
I have already made the revision and you must correct some things

2024-04-17 03:25 UTC, Alejandro25AR commented on src/app/pages/home/home.component.ts
Possibly there is a conflict with the avatar-image folder as it is named as avatar-Image with the letter "i" capitalized.

2024-04-17 03:25 UTC, Alejandro25AR commented on src/app/components/custom-Button/custom-button.component.css
Lowercase the folder name to "custon-button".

2024-04-17 03:25 UTC, Alejandro25AR commented on src/app/components/avatar-Image/avatar-image.component.css
Lowercase the folder name to "avatar-image".

2024-04-17 03:25 UTC, Alejandro25AR commented on src/app/pages/home/home.component.html
>          <h1 class="text-center title-y">Elegí un avatar y escribí tu nombre</h1>
Change the title to a more neutral tone to "Selecciona un avatar"".

2024-04-17 03:25 UTC, Alejandro25AR commented on src/app/pages/home/home.component.html
> +            placeholder="Escribí tu nombre"
Change the placeholder to "Nombre" only.

2024-04-17 03:25 UTC, Alejandro25AR commented on src/app/pages/home/home.component.html
> +      <app-custom-button (click)="iniciarPartida()">Iniciar partida</app-custom-button>
The button text does not describe the action it actually performs, change it to "Crear sala".

2024-04-17 17:38 UTC, closed without merging